name: NestedSortables
author: ryanmitchell
category: Interface
tags: [sortables, nested]
#docs: http://github.com/ryanmitchell/Nested-Sortables
#demo: http://github.com/ryanmitchell/Nested-Sortables/blob/master/Demos/index.html
#current: 1.0